services:
  - type: web
    name: boton-panico-sisdel-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: sisdel-db
      mountPath: /data
      sizeGB: 1
